# Generated by Django 4.1.3 on 2022-12-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='Plans',
        ),
        migrations.AddField(
            model_name='plan',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Plan_company', to='app.company'),
        ),
    ]
