# Generated by Django 4.1.3 on 2022-12-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_company_plans_plan_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplans',
            name='Company',
        ),
    ]
